# Generated by Django 3.1.2 on 2020-10-23 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0002_auto_20201023_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preference',
            new_name='Prefernce',
        ),
    ]
